### ISSUE TITLE
Milestone 1 Functional Prototype

### ISSUE THREAD

**Issue by djblooky** [IAMColumbia/gp2portfoliogame-djblooky#1]
Proof of Concept include main mechanic
- [x] Create Branch for POC
- [x] Build POC add source to src folder
- [x] Commit milesotne work to branch
- [x] Pull Branch back to Master
- [x] Add POC build to build folder
