### ISSUE TITLE
Milestone 2 Vertical Slice

### ISSUE THREAD

**Issue by djblooky** [IAMColumbia/gp2portfoliogame-djblooky#8]
All Features Submitted for testing
- [x] Create Branch for VS
- [x] Commit milestone work to branch
- [x] Pull VS back to Master
- [x] Add VS build to build folder
